const SUPABASE_URL='https://ynhiqevcvehcrvsddcue.supabase.co';
const SUPABASE_KEY='sb_publishable_PQDBnWCA_AH1qZlqAsDvvQ_21vQt_Dw';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const SUBJECTS=['Filipino','English','Mathematics','Science','Araling Panlipunan','GMRC / VE','MAPEH','TLE'];
let me=null,students=[],grades=[],term='1st Term',importMode='',currentCredential=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function status(t,bad=false){$('dbStatus').innerHTML=`<strong>${bad?'Database Error':'Online Database'}</strong> • ${esc(t)}`}
function loginEmail(v){v=String(v||'').trim().toLowerCase();return v.includes('@')?v:`${v}@bnhs.local`}
function roleName(r){return r==='admin'?'Administrator':r==='adviser'?'Adviser':'Student'}
function initials(n){return String(n||'U').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function toggleSide(){$('side').classList.toggle('open')}
function navItems(){if(me.role==='student')return [['dashboard','Dashboard'],['grades','My Grades'],['profile','Profile']];if(me.role==='adviser')return [['dashboard','Dashboard'],['students','My Learners'],['grades','All Subject Grades'],['import','Import Grades'],['profile','Profile']];return [['dashboard','Dashboard'],['students','Students'],['grades','Grade Records'],['accounts','User Accounts'],['import','Bulk Import'],['profile','Profile']]}
function buildNav(){$('nav').innerHTML='<div class="navTitle">PORTAL MENU</div>'+navItems().map(([id,l])=>`<button data-page="${id}" onclick="showPage('${id}')">${l}</button>`).join('')}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('pageTitle').textContent=navItems().find(x=>x[0]===id)?.[1]||'Portal';renderPage(id);$('side').classList.remove('open')}
async function loadData(){status('Loading…');if(me.role==='student'){let q=await sb.from('bnhs_students').select('*').eq('user_id',me.user_id).maybeSingle();students=q.data?[q.data]:[];grades=[];if(students[0]){let g=await sb.from('bnhs_grades').select('*').eq('student_id',students[0].id);grades=g.data||[]}}else{let s=await sb.from('bnhs_students').select('*').order('full_name');students=s.data||[];let g=await sb.from('bnhs_grades').select('*');grades=g.data||[]}status(`${students.length} learner(s) loaded`)}
async function login(e){e.preventDefault();let u=$('loginUser').value.trim(),p=$('loginPass').value,r=$('loginRole').value;if(!u||!p)return alert('Enter your User ID/email and password.');status('Signing in…');let a=await sb.auth.signInWithPassword({email:loginEmail(u),password:p});if(a.error)return alert(a.error.message);let pr=await sb.from('bnhs_profiles').select('*').eq('user_id',a.data.user.id).maybeSingle();let profile=pr.data;if(!profile){let old=await sb.from('profiles').select('user_id,name,role,active').eq('user_id',a.data.user.id).maybeSingle();if(old.data?.role==='admin'&&old.data?.active!==false)profile={user_id:a.data.user.id,user_code:a.data.user.email,full_name:old.data.name||'Administrator',role:'admin',active:true}}if(!profile||profile.active===false){await sb.auth.signOut();return alert('This account is not authorized for this portal.')}if(profile.role!==r){await sb.auth.signOut();return alert(`This account is registered as ${roleName(profile.role)}.`)}me=profile;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('roleBadge').textContent=roleName(me.role);$('avatar').textContent=initials(me.full_name);buildNav();await loadData();showPage('dashboard')}
async function logout(){await sb.auth.signOut();location.reload()}
function renderPage(id){if(id==='dashboard')renderDashboard();if(id==='students')renderStudents();if(id==='grades')renderGrades();if(id==='accounts')renderAccounts();if(id==='import')renderImport();if(id==='profile')renderProfile()}
function renderDashboard(){let mine=me.role==='student'?students[0]:null;let complete=grades.filter(g=>g.grade!=null).length;let avg=grades.length?Math.round(grades.reduce((a,g)=>a+Number(g.grade||0),0)/grades.length):0;$('dashboard').innerHTML=`<div class="welcome"><h1>Welcome, ${esc(me.full_name||'User')}</h1><p>${me.role==='student'?'View your current grade record and account information.':'Manage school grade records securely online.'}</p></div><div class="cards"><div class="card"><div class="muted">${me.role==='student'?'LRN':'Learners'}</div><div class="metric">${me.role==='student'?esc(mine?.lrn||'—'):students.length}</div></div><div class="card"><div class="muted">Grade Entries</div><div class="metric">${complete}</div></div><div class="card"><div class="muted">${me.role==='student'?'General Average':'Current Term'}</div><div class="metric">${me.role==='student'?(avg||'—'):esc(term.replace(' Term',''))}</div></div><div class="card"><div class="muted">Database</div><div class="metric" style="font-size:18px;color:var(--ok)">ONLINE</div></div></div>`;if(me.role==='adviser'){let noLogin=students.filter(s=>!s.user_id).length;let rows=students.slice(0,10).map((s,i)=>`<tr><td><strong>${esc(s.full_name)}</strong><div class="muted">${esc(s.lrn||'No LRN')}</div></td><td><code>${esc(s.user_code||'Will be generated')}</code></td><td><span class="pill ${s.user_id?'ok':'pending'}">${s.user_id?'Login Active':'No Login'}</span></td><td><button class="btn ${s.user_id?'outline':'primary'}" onclick="manageStudentLogin(${i})">${s.user_id?'Reset & Show Details':'Create Login Details'}</button></td></tr>`).join('');$('dashboard').insertAdjacentHTML('beforeend',`<div class="panel"><div class="panelHead"><div><h3>Student Login Details</h3><div class="muted">${noLogin} learner(s) still need login accounts.</div></div><button class="btn outline" onclick="showPage('students')">View All Learners</button></div><div class="tableWrap"><table><thead><tr><th>Learner</th><th>User ID</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows||'<tr><td colspan="4" class="empty">No assigned learners yet.</td></tr>'}</tbody></table></div></div>`)}else if(me.role!=='student'){$('dashboard').insertAdjacentHTML('beforeend',`<div class="panel"><div class="panelHead"><h3>Quick Actions</h3></div><div class="panelBody"><button class="btn primary" onclick="showPage('students')">Manage Learners</button> <button class="btn outline" onclick="showPage('import')">Bulk Import</button></div></div>`)} }
function renderStudents(){let rows=students.map((s,i)=>`<tr><td>${esc(s.lrn||'—')}</td><td><code>${esc(s.user_code||'Not generated')}</code></td><td><strong>${esc(s.full_name)}</strong></td><td>${esc(s.grade_level||'—')} – ${esc(s.section_name||'—')}</td><td>${esc(s.sex||'—')}</td><td><span class="pill ${s.user_id?'ok':'pending'}">${s.user_id?'Login Active':'No Login'}</span></td><td>${me.role==='admin'||me.role==='adviser'?`<button class="btn outline" onclick="manageStudentLogin(${i})">${s.user_id?'Login Details':'Create Login'}</button> `:''}<button class="btn outline danger" onclick="deleteStudent(${i})">Delete</button></td></tr>`).join('');$('students').innerHTML=`<div class="toolbar"><div><h2 style="margin:0">${me.role==='adviser'?'My Learners':'Students / Learners'}</h2><div class="muted">${students.length} learner(s) in the online database.</div></div><div class="group"><button class="btn outline" onclick="openFile('students')">Bulk Add Students</button><button class="btn primary" onclick="openStudentModal()">+ Add Learner</button></div></div><div class="panel"><div class="tableWrap"><table><thead><tr><th>LRN</th><th>User ID</th><th>Name</th><th>Grade & Section</th><th>Sex</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="7" class="empty">No learners yet.</td></tr>'}</tbody></table></div></div>`}
function gradeFor(s,subject){return grades.find(g=>g.student_id===s.id&&g.term===term&&g.subject===subject)?.grade??''}
function renderGrades(){if(me.role==='student'){let s=students[0],rows=SUBJECTS.map(sub=>{let vals=['1st Term','2nd Term','3rd Term'].map(t=>grades.find(g=>g.student_id===s?.id&&g.term===t&&g.subject===sub)?.grade??'—');let nums=vals.filter(x=>x!=='—').map(Number),fin=nums.length?Math.round(nums.reduce((a,b)=>a+b,0)/nums.length):'—';return `<tr><td>${sub}</td><td>${vals[0]}</td><td>${vals[1]}</td><td>${vals[2]}</td><td><strong>${fin}</strong></td><td>${fin==='—'?'—':fin>=75?'<span class="pill ok">Passed</span>':'<span class="pill bad">Failed</span>'}</td></tr>`}).join('');$('grades').innerHTML=`<div class="toolbar"><div><h2 style="margin:0">My Grades</h2><div class="muted">Recorded grades for ${esc(s?.full_name||'learner')}.</div></div></div><div class="panel"><div class="tableWrap"><table><thead><tr><th>Subject</th><th>1st Term</th><th>2nd Term</th><th>3rd Term</th><th>Final</th><th>Remarks</th></tr></thead><tbody>${rows}</tbody></table></div></div>`;return}let rows=students.map((s,i)=>`<tr><td>${esc(s.lrn||'—')}</td><td><strong>${esc(s.full_name)}</strong></td>${SUBJECTS.map(sub=>`<td><input class="gradeInput" type="number" min="0" max="100" value="${gradeFor(s,sub)}" onchange="saveGrade(${i},'${sub.replaceAll("'","\\'")}',this.value)"></td>`).join('')}</tr>`).join('');$('grades').innerHTML=`<div class="toolbar"><div><h2 style="margin:0">All Subject Grades</h2><div class="muted">Changes save directly to Supabase.</div></div><select onchange="term=this.value;renderGrades()"><option ${term==='1st Term'?'selected':''}>1st Term</option><option ${term==='2nd Term'?'selected':''}>2nd Term</option><option ${term==='3rd Term'?'selected':''}>3rd Term</option></select></div><div class="panel"><div class="tableWrap"><table><thead><tr><th>LRN</th><th>Learner</th>${SUBJECTS.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="10" class="empty">No learners yet.</td></tr>'}</tbody></table></div></div>`}
async function saveGrade(i,subject,value){let s=students[i],n=Number(value);if(!s||value===''||Number.isNaN(n)||n<0||n>100)return status('Invalid grade',true);let payload={student_id:s.id,term,subject,grade:n,status:'draft'};if(me.role==='adviser')payload.adviser_user_id=me.user_id;let r=await sb.from('bnhs_grades').upsert(payload,{onConflict:'student_id,term,subject'});if(r.error)return status(r.error.message,true);await loadData();status('Grade saved')}
async function manageStudentLogin(i){let s=students[i];if(!s)return;if(me.role==='adviser'&&s.adviser_user_id&&s.adviser_user_id!==me.user_id)return alert('You may only manage login details for learners assigned to you.');let body;if(s.user_id){if(!confirm(`Generate a new temporary password for ${s.full_name}? The previous password will stop working.`))return;body={action:'reset_student_password',role:'student',student_id:s.id}}else body={role:'student',student_id:s.id,user_code:s.user_code||null,full_name:s.full_name};status('Generating login details…');let r=await sb.functions.invoke('bnhs-create-user',{body});if(r.error||!r.data?.ok)return alert(r.data?.error||r.error?.message||'Could not generate login details.');await loadData();let refreshed=students.find(x=>x.id===s.id)||s;showCredential(refreshed,r.data.user_code,r.data.temporary_password);renderPage(document.querySelector('.page.active')?.id||'dashboard');status('Login details ready')}
function showCredential(s,userCode,password){currentCredential={student:s,userCode,password};$('credentialBody').innerHTML=`<div class="note"><strong>Give these details directly to the learner.</strong><br>The temporary password is shown only when created or reset.</div><div class="field"><label>Student</label><input readonly value="${esc(s.full_name)}"></div><div class="field"><label>LRN</label><input readonly value="${esc(s.lrn||'—')}"></div><div class="field"><label>User ID</label><input readonly value="${esc(userCode)}"></div><div class="field"><label>Temporary Password</label><input readonly value="${esc(password)}"></div>`;$('credentialModal').classList.add('show')}
function closeCredentialModal(){$('credentialModal').classList.remove('show')}
async function copyCredentialDetails(){if(!currentCredential)return;let c=currentCredential,text=`Bingao NHS Grade Portal\nStudent: ${c.student.full_name}\nLRN: ${c.student.lrn||'—'}\nUser ID: ${c.userCode}\nTemporary Password: ${c.password}`;try{await navigator.clipboard.writeText(text);alert('Login details copied.')}catch(e){prompt('Copy login details:',text)}}
function printCredentialDetails(){if(!currentCredential)return;let c=currentCredential,w=window.open('','_blank','width=700,height=600');w.document.write(`<html><head><title>Student Login Slip</title><style>body{font-family:Arial;padding:34px;color:#17324d}.slip{border:2px solid #0b4ea2;border-radius:14px;padding:26px;max-width:600px;margin:auto}.box{background:#f4f8fd;border:1px solid #d7e4f2;border-radius:10px;padding:14px;margin-top:14px}.label{font-size:11px;color:#65758a;font-weight:700}.value{font-size:19px;font-weight:800;margin-top:4px}h1{color:#0b4ea2}</style></head><body><div class="slip"><h1>Bingao National High School</h1><p>Grade Portal Login Details</p><div class="box"><div class="label">Student</div><div class="value">${esc(c.student.full_name)}</div></div><div class="box"><div class="label">LRN</div><div class="value">${esc(c.student.lrn||'—')}</div></div><div class="box"><div class="label">User ID</div><div class="value">${esc(c.userCode)}</div></div><div class="box"><div class="label">Temporary Password</div><div class="value">${esc(c.password)}</div></div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function renderAccounts(){if(me.role!=='admin')return;$('accounts').innerHTML=`<div class="toolbar"><div><h2 style="margin:0">User Accounts</h2><div class="muted">Generate Adviser and Administrator accounts.</div></div><div class="group"><button class="btn outline" onclick="createStaff('adviser')">+ Add Adviser</button><button class="btn primary" onclick="createStaff('admin')">+ Add Admin</button></div></div><div id="accountTable" class="panel"><div class="empty">Loading accounts…</div></div>`;loadAccounts()}
async function loadAccounts(){let q=await sb.from('bnhs_profiles').select('user_id,user_code,full_name,role,active,created_at').in('role',['admin','adviser']).order('created_at');let rows=(q.data||[]).map(a=>`<tr><td><strong>${esc(a.full_name)}</strong></td><td>${roleName(a.role)}</td><td><code>${esc(a.user_code)}</code></td><td><span class="pill ${a.active?'ok':'bad'}">${a.active?'Active':'Inactive'}</span></td><td><small>${esc(a.user_id)}</small></td></tr>`).join('');$('accountTable').innerHTML=`<div class="tableWrap"><table><thead><tr><th>Name</th><th>Role</th><th>User ID</th><th>Status</th><th>Auth UUID</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty">No accounts yet.</td></tr>'}</tbody></table></div>`}
async function createStaff(role){let name=prompt(`Enter ${roleName(role)} full name:`);if(!name?.trim())return;let r=await sb.functions.invoke('bnhs-create-user',{body:{role,full_name:name.trim()}});if(r.error||!r.data?.ok)return alert(r.data?.error||r.error?.message||'Could not create account.');alert(`${roleName(role)} account created.\n\nUser ID: ${r.data.user_code}\nTemporary Password: ${r.data.temporary_password}`);loadAccounts()}
function renderImport(){$('import').innerHTML=`<div class="toolbar"><div><h2 style="margin:0">Bulk Import</h2><div class="muted">Upload one-sheet Excel files. Match learners by LRN first, then name.</div></div></div><div class="cards" style="grid-template-columns:repeat(2,1fr)"><div class="card"><h3>Bulk Add Students</h3><p class="muted">LRN, Name, Grade Level, Section, Sex.</p><button class="btn primary" onclick="openFile('students')">Choose Student File</button></div><div class="card"><h3>Bulk Import Grades</h3><p class="muted">LRN, Name, Grade Level, Section, Term and subject columns.</p><button class="btn primary" onclick="openFile('grades')">Choose Grade File</button></div></div><div id="importResult" class="panel"><div class="empty">No file selected.</div></div>`}
function openFile(m){importMode=m;$('fileInput').value='';$('fileInput').click()}
function norm(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ')}
function findHeader(rows){for(let i=0;i<Math.min(rows.length,10);i++){let h=rows[i].map(norm);if(h.includes('lrn')&&(h.includes('name')||h.some(x=>x.includes('student name'))))return i}return 0}
function val(row,names){for(let k of Object.keys(row))if(names.includes(norm(k)))return row[k];return ''}
async function handleFile(file){if(!file)return;try{status('Reading file…');let data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});let hi=findHeader(raw),headers=raw[hi].map(x=>String(x).trim()),objects=raw.slice(hi+1).filter(r=>r.some(x=>String(x).trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]])));if(importMode==='students')await importStudents(objects);else await importGrades(objects)}catch(e){status(e.message,true);$('importResult').innerHTML=`<div class="panelBody"><strong>Upload failed.</strong><div class="muted">${esc(e.message)}</div></div>`}}
async function importStudents(rows){let added=0,issues=[];for(let r of rows){let lrn=String(val(r,['lrn'])).trim(),name=String(val(r,['name','student name','learner name','full name'])).trim(),gl=String(val(r,['grade level','grade'])).trim(),sec=String(val(r,['section'])).trim(),sex=String(val(r,['sex','gender'])).trim();if(!name||!gl||!sec){issues.push(name||lrn||'Unknown');continue}let p={lrn:lrn||null,full_name:name,grade_level:gl,section_name:sec,sex:sex||null,active:true};if(me.role==='adviser')p.adviser_user_id=me.user_id;let q=lrn?await sb.from('bnhs_students').upsert(p,{onConflict:'lrn'}):await sb.from('bnhs_students').insert(p);if(!q.error)added++;else issues.push(`${name}: ${q.error.message}`)}await loadData();$('importResult').innerHTML=`<div class="panelBody"><strong>${added} learner(s) imported.</strong><div class="muted">${issues.length} issue(s).</div></div>`;status('Student import complete')}
async function importGrades(rows){let added=0,newLearners=0,issues=[];for(let r of rows){let lrn=String(val(r,['lrn'])).trim(),name=String(val(r,['name','student name','learner name','full name'])).trim(),gl=String(val(r,['grade level','grade'])).trim(),sec=String(val(r,['section'])).trim(),t=String(val(r,['term','grading period'])).trim()||term;let s=students.find(x=>lrn&&x.lrn===lrn)||students.find(x=>norm(x.full_name)===norm(name));if(!s&&name){let p={lrn:lrn||null,full_name:name,grade_level:gl||'Grade 7',section_name:sec||'Pegasus',active:true};if(me.role==='adviser')p.adviser_user_id=me.user_id;let ins=await sb.from('bnhs_students').insert(p).select().single();if(ins.data){s=ins.data;students.push(s);newLearners++}else issues.push(`${name}: ${ins.error?.message||'Could not add learner'}`)}if(!s)continue;for(let sub of SUBJECTS){let aliases=[norm(sub)];if(sub==='GMRC / VE')aliases.push('gmrc ve','gmrcve','gmrc');if(sub==='Araling Panlipunan')aliases.push('ap');if(sub==='Mathematics')aliases.push('math');let v=val(r,aliases);if(v===''||v==null)continue;let n=Number(v);if(Number.isNaN(n)||n<0||n>100){issues.push(`${name} - ${sub}`);continue}let p={student_id:s.id,term:t,subject:sub,grade:n,status:'draft'};if(me.role==='adviser')p.adviser_user_id=me.user_id;let q=await sb.from('bnhs_grades').upsert(p,{onConflict:'student_id,term,subject'});if(!q.error)added++;else issues.push(`${name} - ${sub}: ${q.error.message}`)}}await loadData();$('importResult').innerHTML=`<div class="panelBody"><strong>${added} grade(s) imported.</strong><div class="muted">${newLearners} new learner(s) automatically added • ${issues.length} issue(s).</div></div>`;status('Grade import complete')}
function renderProfile(){$('profile').innerHTML=`<div class="panel"><div class="panelHead"><h3>My Profile</h3></div><div class="panelBody"><div class="grid2"><div class="field"><label>Full Name</label><input value="${esc(me.full_name||'')}" disabled></div><div class="field"><label>Role</label><input value="${roleName(me.role)}" disabled></div><div class="field"><label>User ID</label><input value="${esc(me.user_code||'')}" disabled></div><div class="field"><label>Internal Auth UUID</label><input value="${esc(me.user_id||'')}" disabled></div></div></div></div>`}
function openStudentModal(){$('studentModal').classList.add('show')}function closeModal(){$('studentModal').classList.remove('show');$('studentForm').reset()}
async function saveStudent(e){e.preventDefault();let p={lrn:$('fLrn').value.trim()||null,full_name:$('fName').value.trim(),grade_level:$('fGrade').value,section_name:$('fSection').value.trim(),sex:$('fSex').value||null,active:true};if(me.role==='adviser')p.adviser_user_id=me.user_id;let q=p.lrn?await sb.from('bnhs_students').upsert(p,{onConflict:'lrn'}):await sb.from('bnhs_students').insert(p);if(q.error)return alert(q.error.message);closeModal();await loadData();renderStudents();status('Learner saved')}
async function deleteStudent(i){let s=students[i];if(!s||!confirm(`Delete ${s.full_name}? This also removes their grades.`))return;let q=await sb.from('bnhs_students').delete().eq('id',s.id);if(q.error)return alert(q.error.message);await loadData();renderStudents();status('Learner deleted')}
$('loginForm').addEventListener('submit',login);$('studentForm').addEventListener('submit',saveStudent);$('fileInput').addEventListener('change',e=>handleFile(e.target.files[0]));
(async()=>{let ses=await sb.auth.getSession();if(!ses.data.session)return;let p=await sb.from('bnhs_profiles').select('*').eq('user_id',ses.data.session.user.id).maybeSingle();if(!p.data)return;me=p.data;$('login').classList.add('hidden');$('app').classList.remove('hidden');$('roleBadge').textContent=roleName(me.role);$('avatar').textContent=initials(me.full_name);buildNav();await loadData();showPage('dashboard')})().catch(e=>status(e.message,true));